# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{c2dm_on_rails}
  s.version = "0.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julius de Bruijn", "Matteo Centenaro"]
  s.date = %q{2011-08-18}
  s.description = %q{C2DM on Rails is a Ruby on Rails gem that allows you to
easily add Android Cloud to Device Messaging support to your Rails application.
}
  s.email = %q{bugant@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "Manifest",
    "README.textile",
    "Rakefile",
    "VERSION",
    "generators/c2dm_migrations_generator.rb",
    "generators/templates/c2dm_migrations/001_create_c2dm_devices.rb",
    "generators/templates/c2dm_migrations/002_create_c2dm_notifications.rb",
    "lib/c2dm_on_rails.rb",
    "lib/c2dm_on_rails/app/models/c2dm/base.rb",
    "lib/c2dm_on_rails/app/models/c2dm/device.rb",
    "lib/c2dm_on_rails/app/models/c2dm/notification.rb",
    "lib/c2dm_on_rails/c2dm_on_rails.rb",
    "lib/c2dm_on_rails/libs/connection.rb",
    "lib/c2dm_on_rails/tasks/c2dm.rake",
    "lib/c2dm_on_rails_tasks.rb"
  ]
  s.homepage = %q{http://github.com/bugant/c2dm_on_rails}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Android Cloud to Device Messaging (push notifications) on Rails}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

